version: '2'
services:
  web-test:
    image: rawmind/web-test
    tty: true
    labels:
      traefik.port: '8080'
      traefik.domain: dev.local
      traefik.enable: stack
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
