ldap:
  image: beli/ldap:latest
  volumes:
    - /home/claudio/docker/ldap/config:/config
    - /home/claudio/docker/ldap/data:/data
  environment:
    - CONF_ROOTPW="password"
    - CONF_BASEDN="dc=test,dc=com"
  expose:
    - "389"
  labels:
  #   traefik.port: '8080'
  #   traefik.domain: dev.local
  #   traefik.enable: stack
    io.rancher.scheduler.affinity:host_label: purpose=manage
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
