.catalog:
  name: LDAP Container
  version: 2.19.4-rancher1
  description: |
    Simple LDAP

ldap:
  scale: 1
  start_on_create: true
  # health_check:
  #   healthy_threshold: 2
  #   response_timeout: 2000
  #   port: 8080
  #   unhealthy_threshold: 3
  #   initializing_timeout: 60000
  #   interval: 2000
  #   strategy: none
  #   request_line: GET "/login" "HTTP/1.0"